version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/nanali

permissions:
  - object: /home/ubuntu/
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ubuntu