name: Build and Deploy Spring Boot to AWS EC2

on:
  push:
    branches: [main]

env:
  PROJECT_NAME: Nanali
  BUCKET_NAME: nanali
  CODE_DEPLOY_APP_NAME: nanali
  DEPLOYMENT_GROUP_NAME: nanali_deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - uses: actions/checkout@v2
      - run: touch ./src/main/resources/application.properties
      - run: echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.properties

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

      - name: Modify application.properties
        run: |
           sed -i 's~spring.datasource.url =.*~spring.datasource.url = '"${{ secrets.DB_URL }}"'~' ./src/main/resources/application.properties
           sed -i 's~spring.datasource.username =.*~spring.datasource.username = '"${{ secrets.DB_username }}"'~' ./src/main/resources/application.properties
           sed -i 's~spring.datasource.password =.*~spring.datasource.password = '"${{ secrets.DB_password }}"'~' ./src/main/resources/application.properties
           sed -i 's~cloud.aws.credentials.access-key =.*~cloud.aws.credentials.access-key = '"${{ secrets.AWS_ACCESS_KEY_ID }}"'~' ./src/main/resources/application.properties
           sed -i 's~cloud.aws.credentials.secret-key =.*~cloud.aws.credentials.secret-key = '"${{ secrets.AWS_SECRET_ACCESS_KEY }}"'~' ./src/main/resources/application.properties
     
      - name: Make Zip File
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

      - name: Code Deploy
        run: aws deploy create-deployment --application-name $CODE_DEPLOY_APP_NAME --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name $DEPLOYMENT_GROUP_NAME --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
